version: "3.3"
services:
  consul-server-1: &consul-server
    image: consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      - global
  
  consul-server-2:
    <<: *consul-server
    networks:
      - global

  consul-server:
    hostname: consul-server
    <<: *consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    networks:
      - global

  router:
    image: seges/nginx-consul:1.9.0
    volumes:
      - type: bind
        source: ./conf
        target: /etc/consul-template/conf/
      - type: bind
        source: ./templates
        target: /etc/consul-template/templates/
    ports:
      - 800:80
      - 4430:443
    networks:
      - global

  microservice:
    build:
      context: ./
      dockerfile: service.dockerfile
    volumes:
      - type: bind
        source: ./conf
        target: /etc/config/
    environment:
      - SERVICE_NAME=micro
      - SERVICE_TAGS=global,api
    networks:
      - global

networks:
  global: