version: "3.3"
services:
  router:
    image: seges/nginx-consul:1.9.0
    volumes:
      - ./conf: /etc/consul-template/conf/
      - ./templates: /etc/consul-template/templates/
    ports:
      - 80:80
      - 443:443
    networks:
      - global

  microservice:
    build:
      context: ./
      dockerfile: service.dockerfile
    volumes:
      - ./conf: /etc/config/
    environment:
      - SERVICE_NAME=micro
      - SERVICE_TAGS=global,api
    networks:
      - global

networks:
  global: