configuration:
  build:
    context: ./
    dockerfile: configuration.dockerfile

router:
  image: seges/nginx-consul:1.9.0
  volumes_from:
    - configuration
  ports:
    - 80:80
    - 443:443

microservice:
  build:
    context: ./
    dockerfile: service.dockerfile
  volumes_from:
    - configuration
  environment:
    - SERVICE_NAME=micro
    - SERVICE_TAGS=global,api
